### PR TITLE
Introduce edd_items_not_in_cart shortcode #9

### LINKED ISSUE #9: items_not_in_cart?
Hello @cklosowski , this is a possible enhancement to this extension. Perhaps an edd_items_not_in_cart shortcode?

Where we could show/hide content based on certain items NOT being in the cart. :)

Thanks!

### PR DESCRIPTION
**Pull request by ashleyfae**
Closes #9

Content inside the shortcode should only be displayed if your cart does NOT contain the specified item(s).

Content shows if cart does not contain download 20:

```
[edd_items_not_in_cart ids="20"]Content here[/edd_items_not_in_cart]
```

Content shows if cart does not contain either download 20, 34, or 25 price ID 1 (if any one is missing, content shows):

```
[edd_items_not_in_cart ids="20,34,25:1"]Content Here[/edd_items_not_in_cart]

[edd_items_not_in_cart ids="20,34,25:1" match="any"]Content Here[/edd_items_not_in_cart]
```

Content shows if cart does not contain all of these downloads at the same time: ID 20, 34, and ID 25 price ID 1:

```
[edd_items_not_in_cart ids="20,34,25:1" match="all"]Content Here[/edd_items_not_in_cart]
```

### CODE REVIEW

**Review by robincornett — COMMENTED** [review]
I'm trying to think through mentally how "any" and "all" will play out differently in real life and I'm feeling really obtuse because I don't think they're going to end up being different, are they?

In my store, I've set up two shortcodes:

```
[edd_items_not_in_cart ids="18,22"]This will show if ANY of the items are not in the cart.[/edd_items_not_in_cart]
[edd_items_not_in_cart ids="18,22" match="all"]This will show if ALL of the items are not in the cart.[/edd_items_not_in_cart]
```

I've added item 18 to the cart and not item 22 and I think the "all" is not working correctly regardless, as the second shortcode content is not displaying. But as I'm thinking about it, it feels like "all" should be following the same logic as "any" ... if any of the downloads are not in the cart, then the shortcode content should show, shouldn't it?

Also feeling like if someone accidentally uses the shortcode without any `$content` there should just be an immediate early return.

**Comment by LisaCee** [comment]
This is a tricky one to wrap my head around, so I'm going to try to talk it out here and please correct me if it's wrong.

`[edd_items_not_in_cart ids="44,53,59" ]Any of 3-items[/edd_items_not_in_cart]`
If any of these items are not in my cart I should see this message.  I could have 1 or 2 items in my cart and see the message, just not all 3.

vs

`[edd_items_not_in_cart ids="44,53,59" match="all"]None of these 3-items[/edd_items_not_in_cart]` 
If none of these items is in my cart I should see the message.  If any of these items are in my cart I will not see the message.

Is that right?

A couple of quick thoughts:
- I agree that we should exit if there is no `$content`.  I could see people trying to troubleshoot why they are not seeing a message, thinking that the shortcode isn't working, when really there is no content to show.
- Since it's possible to have more than one of these shortcodes, could we make it so they are `display: block`?  I had a couple of these shortcodes on the same page and the messages were output next to each other.

**Comment by robincornett** [comment]
ahhh @LisaCee thank you for explaining that. It makes sense. Based on that, then, should the attribute choices be "any" and "none" then?

I also agree about the multiple shortcodes--it would be nice to at least wrap the output in a `<div>`, if not apply `wpautop` at the very least. However, none of the other shortcodes in the plugin have any kind of additional markup added that I can see so I do wonder about adding it here, as it would make the new shortcode inconsistent with the old.

**Comment by LisaCee** [comment]
> Based on that, then, should the attribute choices be "any" and "none" then?

I like that wording better.

**Comment by robincornett** [comment]
@ashleyfae I was reviewing this milestone and it looks like this particular issue kind of stalled. Does the discussion about the `match` attribute seem reasonable to you (changing "all" to "none")?

Also see what you think about the question of markup or whether we should leave that alone to be consistent.

**Review by robincornett — APPROVED** [review]
I take it back. It makes more sense to me to keep the `match` parameter consistent with the existing shortcodes and this does, and it works, so I'm ready to approve.

**Pull request merged**
